'use strict';

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const srcPages = path.join(root, 'src', 'pages');
const srcPartials = path.join(root, 'src', 'partials');

// ── 1. Process HTML templates ───────────────────────────────────

const INCLUDE_RE = /^(\s*)<!--\s*@include\s+([\w/._-]+)\s*-->\s*$/gm;

const partialCache = {};

function readPartial(name) {
    if (partialCache[name]) return partialCache[name];
    const filePath = path.join(root, 'src', name);
    if (!fs.existsSync(filePath)) {
        console.warn(`  ⚠  Partial not found: ${name}`);
        return '';
    }
    const content = fs.readFileSync(filePath, 'utf8');
    partialCache[name] = content;
    return content;
}

function processIncludes(html) {
    let out = html;
    let prev;
    do {
        prev = out;
        out = out.replace(INCLUDE_RE, (_match, _indent, partialPath) => {
            const content = readPartial(partialPath);
            return content.trimEnd();
        });
    } while (out !== prev);
    return out;
}

function buildPages() {
    if (!fs.existsSync(srcPages)) {
        console.warn('No src/pages/ directory — skipping HTML template build.');
        return 0;
    }

    let count = 0;

    function walk(dir) {
        for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
            const fullPath = path.join(dir, entry.name);
            if (entry.isDirectory()) {
                walk(fullPath);
            } else if (entry.name.endsWith('.html')) {
                const relPath = path.relative(srcPages, fullPath);
                const destPath = path.join(root, relPath);
                const destDir = path.dirname(destPath);
                if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });

                const template = fs.readFileSync(fullPath, 'utf8');
                const output = processIncludes(template);
                fs.writeFileSync(destPath, output, 'utf8');
                count++;
            }
        }
    }

    walk(srcPages);
    return count;
}

const pageCount = buildPages();
if (pageCount > 0) {
    console.log(`Built ${pageCount} HTML page(s) from src/pages/.`);
}

// ── 2. Inject Supabase runtime config ───────────────────────────

function parseEnvFile(filePath) {
    if (!fs.existsSync(filePath)) return {};
    const out = {};
    for (const line of fs.readFileSync(filePath, 'utf8').split('\n')) {
        const t = line.trim();
        if (!t || t.startsWith('#')) continue;
        const eq = t.indexOf('=');
        if (eq === -1) continue;
        const key = t.slice(0, eq).trim();
        let val = t.slice(eq + 1).trim();
        if (
            (val.startsWith('"') && val.endsWith('"')) ||
            (val.startsWith("'") && val.endsWith("'"))
        ) {
            val = val.slice(1, -1);
        }
        out[key] = val;
    }
    return out;
}

const fileEnv = parseEnvFile(path.join(root, '.env'));
const url = process.env.SUPABASE_URL || fileEnv.SUPABASE_URL || '';
const key = process.env.SUPABASE_ANON_KEY || fileEnv.SUPABASE_ANON_KEY || '';
const bucket =
    process.env.SUPABASE_STORAGE_BUCKET ||
    fileEnv.SUPABASE_STORAGE_BUCKET ||
    'ART';

const outPath = path.join(root, 'static/js/supabase-runtime.js');

if (!url || !key) {
    console.warn(
        'Missing SUPABASE_URL or SUPABASE_ANON_KEY — writing empty supabase-runtime.js so the build can finish. ' +
            'For local dev, copy .env.example to .env. On Vercel, add those variables under Project → Settings → Environment Variables and redeploy.'
    );
    const stub =
        '/* Generated by npm run build — no Supabase env; blog/admin need Vercel env vars */\n' +
        'window.__SUPABASE_URL__="";\n' +
        'window.__SUPABASE_ANON_KEY__="";\n' +
        `window.__SUPABASE_STORAGE_BUCKET__=${JSON.stringify(bucket)};\n`;
    fs.writeFileSync(outPath, stub, 'utf8');
    console.log('Wrote', path.relative(root, outPath), '(stub)');
} else {
    const body =
        '/* Generated by npm run build — do not edit */\n' +
        `window.__SUPABASE_URL__=${JSON.stringify(url)};\n` +
        `window.__SUPABASE_ANON_KEY__=${JSON.stringify(key)};\n` +
        `window.__SUPABASE_STORAGE_BUCKET__=${JSON.stringify(bucket)};\n`;
    fs.writeFileSync(outPath, body, 'utf8');
    console.log('Wrote', path.relative(root, outPath));
}
