-- Supabase → SQL → New query (run once, or re-run: storage policies use DROP IF EXISTS).
--
-- Mag articles + storage for the Vic Valentine admin + public site.
--
-- Image paths (must match the app):
--   • Bucket id = value of SUPABASE_STORAGE_BUCKET in .env (default: ART).
--   • DB columns `cover_image` and block `filename` values are object keys only, e.g.
--       my-post-slug/a1b2c3d4-....jpg
--       uploads/cover-a1b2c3d4-....jpg
--   • Public URL = {SUPABASE_URL}/storage/v1/object/public/{BUCKET}/{path}
--     (see storageUrl() in static/js/config.js).
--
-- After this, run admin logged in: uploads use db.storage.from(STORAGE_BUCKET).upload(path, file).

-- ── Storage bucket (public read for those URLs) ───────────────────────────

insert into storage.buckets (id, name, public)
values ('ART', 'ART', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "Public read art storage" on storage.objects;
create policy "Public read art storage"
  on storage.objects for select
  using (bucket_id = 'ART');

drop policy if exists "Authenticated insert art storage" on storage.objects;
create policy "Authenticated insert art storage"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'ART');

drop policy if exists "Authenticated update art storage" on storage.objects;
create policy "Authenticated update art storage"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'ART')
  with check (bucket_id = 'ART');

drop policy if exists "Authenticated delete art storage" on storage.objects;
create policy "Authenticated delete art storage"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'ART');

-- ── Posts table (matches admin/edit + mag/post pages) ───────────────────
-- id: integer — admin uses parseInt(id) in the query string.
-- published: 0 or 1 — .eq('published', 1) on public pages; checkbox in admin.

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null default '',
  subheading text not null default '',
  slug text not null,
  body text not null default '[]',
  body_html text,
  cover_image text,
  cover_alt text,
  published smallint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint posts_published_check check (published in (0, 1)),
  constraint posts_slug_unique unique (slug)
);

alter table public.posts
  add column if not exists subheading text not null default '';

create index if not exists posts_published_created_idx
  on public.posts (published, created_at desc);

create index if not exists posts_slug_idx on public.posts (slug);

create or replace function public.posts_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at
  before update on public.posts
  for each row execute function public.posts_touch_updated_at();

alter table public.posts enable row level security;

drop policy if exists "Public read published posts" on public.posts;
create policy "Public read published posts"
  on public.posts for select
  to anon
  using (published = 1);

drop policy if exists "Authenticated read all posts" on public.posts;
create policy "Authenticated read all posts"
  on public.posts for select
  to authenticated
  using (true);

drop policy if exists "Authenticated insert posts" on public.posts;
create policy "Authenticated insert posts"
  on public.posts for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated update posts" on public.posts;
create policy "Authenticated update posts"
  on public.posts for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated delete posts" on public.posts;
create policy "Authenticated delete posts"
  on public.posts for delete
  to authenticated
  using (true);
